export const CARD_BG = [
    { id: 1, bgcolor: "linear-gradient(135deg, #FFBEC8 0%, #FDDDE6 100%)" },
    { id: 2, bgcolor: "linear-gradient(135deg, #82B7FE 0%, #B7E5FF 100%)" },
    { id: 3, bgcolor: "linear-gradient(135deg, #FFA44C 0%, #F9D69E 100%)" },
    { id: 4, bgcolor: "linear-gradient(135deg, #3E8984 0%, #A6E3D1 100%)" },
    { id: 5, bgcolor: "linear-gradient(135deg, #CB82B2 0%, #DFB1D5 100%)" },
    { id: 6, bgcolor: "linear-gradient(135deg, #CD5C5C 0%, #F08080 100%)" },
    { id: 7, bgcolor: "linear-gradient(135deg, #2994C1 0%, #B4E9FF 100%)" },
    { id: 8, bgcolor: "linear-gradient(135deg, #948C0B 0%, #ECECE4 100%)" },
    { id: 9, bgcolor: "linear-gradient(135deg, #E2B4BB 0%, #FFFAF3 100%)" },
    { id: 10, bgcolor: "linear-gradient(135deg, #98AB59 0%, #E9E8E4 100%)" },

];

export const APP_FEATURES = [
    {
        id: "01",
        title: "Tailored Just for You",
        description: 
            "Get interview questions and model answers based on your role, experience, and specic focus areas - no generic practice here."
    },
     {
        id: "02",
        title: "Learn at Your Own Pace",
        description: 
            "Expand answers only when you're ready, Dive deeper into nay concept instantly with AI-powered detailed explanations"
    },
     {
        id: "03",
        title: "Capture Your Insights",
        description: 
            "Add personal notes to any questions and pin important ones to the top - making your learning more organized and impactful."
    },
     {
        id: "04",
        title: 'Understand the "Why" Behind Answers',
        description: 
            "Beyond just answers - unlock detailed concepts explanations generated by AI, helping you truly master each topic."
    },
     {
        id: "05",
        title: "Save, Organize, and Revisit",
        description: 
            "Easily save your interview sets, organize them neatly in your dashboard, and pick up your preperation right where you left off."
    },
]